Repository donnemartin/system-design-primer, pull requests merged in 2020-07, with the labels that each got.

#399 Missing comma
  solutions/system_design/mint/README.md
Labels: needs-review

#398 fix: typo
  README.md
Labels: needs-review

#317 Fix a typo in Layer 7 load balancer of README.md
  README.md
Labels: needs-review

#350 Resolve #164 - Fix phrasing with availability and partition tolerance
  README.md
Labels: needs-review

#406 Check dependencies in Ebook gen script
  generate-epub.sh
Labels: needs-review

#418 Fix typo: Change replication to federation
  solutions/system_design/web_crawler/README.md
Labels: needs-review

#414 Update design Twitter back-of-the-envelope calculations
  solutions/system_design/twitter/README.md
Labels: needs-review

#433 Add system design template link
  README.md
Labels: incorporating-feedback, response-needed

#340 kr: Fix Korean translation link in language index
  README-ja.md
  README-zh-Hans.md
  README-zh-TW.md
  README.md
Labels: help wanted, needs-review, translation

#409 Fix Mint exercise bugs and typos
  solutions/system_design/mint/README.md
Labels: needs-review

#405 Remove redundant SQL index in Pastebin exercise
  solutions/system_design/pastebin/README.md
Labels: needs-review

#400 Add CAP theorem video
  README.md
Labels: needs-review

#396 Fix the loop over "self.cards"
  solutions/object_oriented_design/deck_of_cards/deck_of_cards.ipynb
Labels: needs-review

#321 Update dead links
  README.md
Labels: needs-review

#319 Add links for latency based and geolocation based routing
  README.md
Labels: needs-review

#310 Clarify CDN advantages
  README.md
Labels: needs-review

#295 Change disk to HDD for clarity
  README.md
Labels: needs-review

#441 Resolve #281: Add design stock exchange links
  README.md
Labels: needs-review

#168 Remove Imgur dependency by storing images locally
  README-ja.md
  README-zh-Hans.md
  README-zh-TW.md
  README.md
  images/0vBc0hN.png
  images/4edXG0T.png
  images/4j99mhe.png
  images/54GYsSx.png
  images/5KeocQs.jpg
  images/C9ioGtn.png
  images/IOyLj4i.jpg
  images/JdAsdvG.jpg
  images/MzExP06.png
  images/ONjORqk.png
  images/OfVllex.png
  images/Q6z24La.png
  images/TcUo2fw.png
  images/U3qV33e.png
  images/V5q57vU.png
  images/Xkm5CXz.png
  images/b4YtAEN.png
  images/bWxPtQA.png
  images/bgLMI2u.png
  images/cdCv5g7.png
  images/fNcl65g.png
  images/h81n9iK.png
  images/h9TAuGI.jpg
  images/iF4Mkb5.png
  images/jj3A5N8.png
  images/jrUBAF7.png
  images/krAHLGg.png
  images/kxtjqgE.png
  images/n16iOGk.png
  images/n41Azff.png
  images/rgSrvjG.png
  images/wU8x5Id.png
  images/wXGqG5f.png
  images/yB5SYwm.png
  images/yzDrJtA.jpg
  images/zdCAkB3.png
Labels: needs-review
